---
title: "1_clean_data"
output: html_notebook
---



```{r}
library(tidyverse)
library(janitor)
library(readxl)
library(tools)
library(fs)
```



```{r}
set.seed(1337)
```



```{r}
all_irop <- read_csv('/Volumes/External/irop_data/irop_07092020.csv') %>%
    clean_names() %>%
    filter(reader == 'goldenstandardreading@ohsu.edu') %>%
    mutate(session = str_remove_all(session, '[ a-zA-Z]'),
           posterior = paste(file_path_sans_ext(basename(posterior)), '.bmp', sep = ''),
           nasal = paste(file_path_sans_ext(basename(nasal)), '.bmp', sep = ''),
           temporal = paste(file_path_sans_ext(basename(temporal)), '.bmp', sep = ''),
           inferior = paste(file_path_sans_ext(basename(inferior)), '.bmp', sep = ''),
           superior = paste(file_path_sans_ext(basename(superior)), '.bmp', sep = ''))

split_1 <- read_excel('/Volumes/External/irop_data/all_splits_master_file.xlsx', sheet = 1) %>%
    clean_names() %>%
    separate(original_files, c('subject_id', NA, 'session', NA, 'eye', NA), sep = '_') %>%
    inner_join(all_irop, by = c('subject_id', 'eye', 'session')) %>%
    na_if('NULL.bmp') %>%
    select(subject_id, session, eye, ground_truth, posterior, nasal, temporal, inferior, superior)

split_2 <- read_excel('/Volumes/External/irop_data/all_splits_master_file.xlsx', sheet = 2) %>%
    clean_names() %>%
    separate(original_files, c('subject_id', NA, 'session', NA, 'eye', NA), sep = '_') %>%
    inner_join(all_irop, by = c('subject_id', 'eye', 'session')) %>%
    na_if('NULL.bmp') %>%
    select(subject_id, session, eye, ground_truth, posterior, nasal, temporal, inferior, superior)

split_3 <- read_excel('/Volumes/External/irop_data/all_splits_master_file.xlsx', sheet = 3) %>%
    clean_names() %>%
    separate(original_files, c('subject_id', NA, 'session', NA, 'eye', NA), sep = '_') %>%
    inner_join(all_irop, by = c('subject_id', 'eye', 'session')) %>%
    na_if('NULL.bmp') %>%
    select(subject_id, session, eye, ground_truth, posterior, nasal, temporal, inferior, superior)

split_4 <- read_excel('/Volumes/External/irop_data/all_splits_master_file.xlsx', sheet = 4) %>%
    clean_names() %>%
    separate(original_files, c('subject_id', NA, 'session', NA, 'eye', NA), sep = '_') %>%
    inner_join(all_irop, by = c('subject_id', 'eye', 'session')) %>%
    na_if('NULL.bmp') %>%
    select(subject_id, session, eye, ground_truth, posterior, nasal, temporal, inferior, superior)

split_5 <- read_excel('/Volumes/External/irop_data/all_splits_master_file.xlsx', sheet = 5) %>%
    clean_names() %>%
    separate(original_files, c('subject_id', NA, 'session', NA, 'eye', NA), sep = '_') %>%
    inner_join(all_irop, by = c('subject_id', 'eye', 'session')) %>%
    na_if('NULL.bmp') %>%
    select(subject_id, session, eye, ground_truth, posterior, nasal, temporal, inferior, superior) %>%
    drop_na(posterior)
```


```{r}
gan_no2plus <- split_1 %>%
    bind_rows(split_2) %>%
    filter(ground_truth != 'Pre-Plus') %>%
    gather('view', 'image_id', posterior:superior) %>%
    drop_na() %>%
    filter(ground_truth == 'Plus' | view == 'posterior')
    # %>%
    # group_by(ground_truth) %>%
    # add_count() %>%
    # slice(sample(row_number(), min(.$n))) %>%
    # select(-n)

gan_no2preplus <- split_1 %>%
    bind_rows(split_2) %>%
    filter(ground_truth != 'Plus') %>%
    gather('view', 'image_id', posterior:superior) %>%
    drop_na() %>%
    filter(ground_truth == 'Pre-Plus' | view == 'posterior') # %>%
    # group_by(ground_truth) %>%
    # add_count() %>%
    # slice(sample(row_number(), min(.$n))) %>%
    # select(-n)

gan_preplus2plus <- split_1 %>%
    bind_rows(split_2) %>%
    filter(ground_truth != 'No') %>%
    gather('view', 'image_id', posterior:superior) %>%
    drop_na() #%>%
    # group_by(ground_truth) %>%
    # add_count() %>%
    # slice(sample(row_number(), min(.$n))) %>%
    # select(-n)

cnn_train <- split_3 %>%
    gather('view', 'image_id', posterior:superior) %>%
    drop_na(image_id) # %>%
    # group_by(ground_truth) %>%
    # add_count() %>%
    # slice(sample(row_number(), min(.$n))) %>%
    # select(-n)

cnn_val <- split_4 %>%
    drop_na(posterior) %>%
    group_by(ground_truth) %>%
    add_count() %>%
    slice(sample(row_number(), min(.$n))) %>%
    select(-n)

cnn_test <- split_5 %>%
    drop_na(posterior)
```


```{r}
dir_create('./out/gan/no2plus/images/No')
dir_create('./out/gan/no2plus/images/Plus')

dir_create('./out/gan/no2preplus/images/No')
dir_create('./out/gan/no2preplus/images/Pre-Plus')

dir_create('./out/gan/preplus2plus/images/Pre-Plus')
dir_create('./out/gan/preplus2plus/images/Plus')

dir_create('./out/cnn/train/real/No')
dir_create('./out/cnn/train/real/Pre-Plus')
dir_create('./out/cnn/train/real/Plus')

dir_create('./out/cnn/val/real/No')
dir_create('./out/cnn/val/real/Pre-Plus')
dir_create('./out/cnn/val/real/Plus')

dir_create('./out/cnn/test/real/No')
dir_create('./out/cnn/test/real/Pre-Plus')
dir_create('./out/cnn/test/real/Plus')
```


```{r}
write_csv(gan_no2plus, './out/gan/no2plus/gan_no2plus.csv')
write_csv(gan_no2preplus, './out/gan/no2preplus/gan_no_preplus.csv')
write_csv(gan_preplus2plus, './out/gan/preplus2plus/gan_preplus_plus.csv')
write_csv(cnn_train, './out/cnn/train/cnn_train.csv')
write_csv(cnn_val, './out/cnn/val/cnn_val.csv')
write_csv(cnn_test, './out/cnn/test/cnn_test.csv')
```


```{r}
src = '/Volumes/Storage/irop_data/segmentations'

dst = './out/gan/no2plus/images'
file_copy(paste(src, gan_no2plus$image_id, sep = '/'), paste(dst, gan_no2plus$ground_truth, gan_no2plus$image_id, sep = '/'), overwrite = TRUE)

dst = './out/gan/no2preplus/images'
file_copy(paste(src, gan_no2preplus$image_id, sep = '/'), paste(dst, gan_no2preplus$ground_truth, gan_no2preplus$image_id, sep = '/'), overwrite = TRUE)

dst = './out/gan/preplus2plus/images'
file_copy(paste(src, gan_preplus2plus$image_id, sep = '/'), paste(dst, gan_preplus2plus$ground_truth, gan_preplus2plus$image_id, sep = '/'), overwrite = TRUE)

dst = './out/cnn/train/real'
file_copy(paste(src, cnn_train$image_id, sep = '/'), paste(dst, cnn_train$ground_truth, cnn_train$image_id, sep = '/'), overwrite = TRUE)

dst = './out/cnn/val/real'
file_copy(paste(src, cnn_val$posterior, sep = '/'), paste(dst, cnn_val$ground_truth, cnn_val$posterior, sep = '/'), overwrite = TRUE)

dst = './out/cnn/test/real'
file_copy(paste(src, cnn_test$posterior, sep = '/'), paste(dst, cnn_test$ground_truth, cnn_test$posterior, sep = '/'), overwrite = TRUE)
```



```{r}
file_move('./out/gan/no2plus/images/No', './out/gan/no2plus/images/trainA')
file_move('./out/gan/no2plus/images/Plus', './out/gan/no2plus/images/trainB')

file_move('./out/gan/no2preplus/images/No', './out/gan/no2preplus/images/trainA')
file_move('./out/gan/no2preplus/images/Pre-Plus', './out/gan/no2preplus/images/trainB')

file_move('./out/gan/preplus2plus/images/Pre-Plus', './out/gan/preplus2plus/images/trainA')
file_move('./out/gan/preplus2plus/images/Plus', './out/gan/preplus2plus/images/trainB')


file_move('./out/cnn/train/real/No', './out/cnn/train/real/1')
file_move('./out/cnn/train/real/Pre-Plus', './out/cnn/train/real/2')
file_move('./out/cnn/train/real/Plus', './out/cnn/train/real/3')

file_move('./out/cnn/val/real/No', './out/cnn/val/real/1')
file_move('./out/cnn/val/real/Pre-Plus', './out/cnn/val/real/2')
file_move('./out/cnn/val/real/Plus', './out/cnn/val/real/3')

file_move('./out/cnn/test/real/No', './out/cnn/test/real/1')
file_move('./out/cnn/test/real/Pre-Plus', './out/cnn/test/real/2')
file_move('./out/cnn/test/real/Plus', './out/cnn/test/real/3')
```


## IMPORTANT: Run 2_clean_images.py before training models!
