---
title: "R Notebook"
output: html_notebook
---


```{r}
library(tidyverse)
library(umap)
library(ggthemes)
```

```{r setup}
knitr::opts_chunk$set(fig.height=7, fig.width=7, dpi=300)

```


# Load data and set UMAP configs
```{r message=FALSE, warning=FALSE}
sets_123_fts <- read_csv('./out/features/real_images_sets_123_features.csv', col_names = F)
set_3_fts <- read_csv('./out/features/real_images_set_3_features.csv', col_names = F)

pgan_fts <- read_csv('./out/features/PGANfeatures.csv', col_names = F)
cyclegan_fwd_fts <- read_csv('./out/features/cyclegan_forward_features.csv', col_names = F)
cyclegan_bwd_fts <- read_csv('./out/features/cyclegan_backward_features.csv', col_names = F)
```

```{r}
config = umap.defaults
config$random_state = 1337
config$min_dist = 0.99
config$metric = 'euclidean'
config$n_neighbors = 25
```


# Generate UMAPs for PGAN data vs real data used to train PGAN
```{r}
sets_123_umap <- umap(sets_123_fts, config = config)
```


```{r}
ggplot() +
    aes(x = V1, y = V2) +
    geom_point(data = as.data.frame(sets_123_umap$layout), color = rep(c('forestgreen', 'orange2', 'red'), times = c(2563, 420, 89)), shape = 19) +
    theme_few() +
    xlim(c(-9, 9)) +
    ylim(c(-9, 9)) +
    ggtitle('UMAP of Real Data Used to Train PGAN')
```


```{r}
pgan_predictions <- pgan_fts %>%
    slice(1:1000, 10001:11000, 20001:21000) %>%
    predict(sets_123_umap, .)
```


```{r}
ggplot() +
    aes(x = V1, y = V2) +
    geom_point(data = as.data.frame(pgan_predictions), color = rep(c('forestgreen', 'orange2', 'red'), times = c(1000, 1000, 1000)), shape = 17) +
    theme_few() +
    xlim(c(-9, 9)) +
    ylim(c(-9, 9)) +
    ggtitle('UMAP of Data Generated by PGAN')
```


```{r}
ggplot() +
    aes(x = V1, y = V2) +
    geom_point(data = as.data.frame(pgan_predictions), color = rep(c('forestgreen', 'orange2', 'red'), times = c(1000, 1000, 1000)), shape = 17, alpha = 1) +
    geom_point(data = as.data.frame(sets_123_umap$layout), color = rep(c('forestgreen', 'orange2', 'red'), times = c(2563, 420, 89)), shape = 19, alpha = 0.25) +
    theme_few() +
    xlim(c(-9, 9)) +
    ylim(c(-9, 9)) +
    ggtitle('Overlay UMAP of Real Data Used to Train PGAN and Generated Data by PGAN')
```






# Generate UMAPs for CycleGAN data vs real data converted by CycleGAN


```{r}
# set_3_umap <- umap(set_3_fts, config = config)
```


```{r}
set_3_predictions <- predict(sets_123_umap, set_3_fts)
```


```{r}
ggplot() +
    aes(x = V1, y = V2) +
    geom_point(data = as.data.frame(set_3_predictions), color = rep(c('forestgreen', 'orange2', 'red'), times = c(927, 168, 40)), shape = 19, size = 2) +
    theme_few() +
    xlim(c(-9, 9)) +
    ylim(c(-9, 9)) +
    ggtitle('UMAP of Data Generated by PGAN')
```




```{r}
cyclegan_fwd_predictions <- predict(sets_123_umap, cyclegan_fwd_fts)
cyclegan_bwd_predictions <- predict(sets_123_umap, cyclegan_bwd_fts)
```


```{r}
ggplot() +
    aes(x = V1, y = V2) +
    geom_point(data = as.data.frame(set_3_predictions), color = rep(c('forestgreen', 'orange2', 'red'), times = c(927, 168, 40)), shape = 19, alpha = 0.25) +
    geom_point(data = slice_head(as.data.frame(set_3_predictions), n = 927), color = 'forestgreen', shape = 19) +
    geom_point(data = slice(as.data.frame(cyclegan_fwd_predictions), 1:(927*2)), color = rep(c('orange2', 'red'), times = c(927, 927)), shape = 17) +
    theme_few() +
    xlim(c(-9, 9)) +
    ylim(c(-9, 9)) +
    ggtitle('Normal to Pre-plus and Plus')
```


```{r}
ggplot() +
    aes(x = V1, y = V2) +
    geom_point(data = as.data.frame(set_3_predictions), color = rep(c('forestgreen', 'orange2', 'red'), times = c(927, 168, 40)), shape = 19, alpha = 0.25) +
    geom_point(data = slice(as.data.frame(set_3_predictions), 928:1095), color = 'orange2', shape = 19, size = 2) +
    geom_point(data = slice_tail(as.data.frame(cyclegan_fwd_predictions), n = 168), color = rep(c('red'), times = c(168)), shape = 17, size = 2) +
    geom_point(data = slice_head(as.data.frame(cyclegan_bwd_predictions), n = 168), color = rep(c('forestgreen'), times = c(168)), shape = 17, size = 2) +
    theme_few() +
    xlim(c(-9, 9)) +
    ylim(c(-9, 9)) +
    ggtitle('Pre-plus to Normal and Plus')
```


```{r}
ggplot() +
    aes(x = V1, y = V2) +
    geom_point(data = as.data.frame(set_3_predictions), color = rep(c('forestgreen', 'orange2', 'red'), times = c(927, 168, 40)), shape = 19, alpha = 0.25) +
    geom_point(data = slice_tail(as.data.frame(set_3_predictions), n = 40), color = 'red', shape = 19, size = 2) +
    geom_point(data = slice(as.data.frame(cyclegan_bwd_predictions), 41:80), color = rep(c('forestgreen'), times = c(40)), shape = 17, size = 2) +
    geom_point(data = slice_tail(as.data.frame(cyclegan_bwd_predictions), n = 40), color = rep(c('orange2'), times = c(40)), shape = 17, size = 2) +
    theme_few() +
    xlim(c(-9, 9)) +
    ylim(c(-9, 9)) +
    ggtitle('Plus to Normal and Pre-plus')
```