---
title: "1_clean_data"
output: html_notebook
---



```{r message=FALSE}
library(tidyverse)
library(janitor)
library(readxl)
library(tools)
library(fs)
```


```{r}
set.seed(1337)
```


```{r message=FALSE}
all_irop <- read_csv('/Volumes/External/irop_data/irop_07092020.csv') %>%
    clean_names() %>%
    filter(reader == 'goldenstandardreading@ohsu.edu') %>%
    mutate(session = str_remove_all(session, '[ a-zA-Z]'),
           posterior = paste(file_path_sans_ext(basename(posterior)), '.bmp', sep = ''),
           nasal = paste(file_path_sans_ext(basename(nasal)), '.bmp', sep = ''),
           temporal = paste(file_path_sans_ext(basename(temporal)), '.bmp', sep = ''),
           inferior = paste(file_path_sans_ext(basename(inferior)), '.bmp', sep = ''),
           superior = paste(file_path_sans_ext(basename(superior)), '.bmp', sep = ''))

split_1 <- read_excel('/Volumes/External/irop_data/all_splits_master_file.xlsx', sheet = 1) %>%
    clean_names() %>%
    separate(original_files, c('subject_id', NA, 'session', NA, 'eye', NA), sep = '_') %>%
    inner_join(all_irop, by = c('subject_id', 'eye', 'session')) %>%
    na_if('NULL.bmp') %>%
    select(subject_id, session, eye, ground_truth, posterior, nasal, temporal, inferior, superior)

split_2 <- read_excel('/Volumes/External/irop_data/all_splits_master_file.xlsx', sheet = 2) %>%
    clean_names() %>%
    separate(original_files, c('subject_id', NA, 'session', NA, 'eye', NA), sep = '_') %>%
    inner_join(all_irop, by = c('subject_id', 'eye', 'session')) %>%
    na_if('NULL.bmp') %>%
    select(subject_id, session, eye, ground_truth, posterior, nasal, temporal, inferior, superior)

split_3 <- read_excel('/Volumes/External/irop_data/all_splits_master_file.xlsx', sheet = 3) %>%
    clean_names() %>%
    separate(original_files, c('subject_id', NA, 'session', NA, 'eye', NA), sep = '_') %>%
    inner_join(all_irop, by = c('subject_id', 'eye', 'session')) %>%
    na_if('NULL.bmp') %>%
    select(subject_id, session, eye, ground_truth, posterior, nasal, temporal, inferior, superior)

split_4 <- read_excel('/Volumes/External/irop_data/all_splits_master_file.xlsx', sheet = 4) %>%
    clean_names() %>%
    separate(original_files, c('subject_id', NA, 'session', NA, 'eye', NA), sep = '_') %>%
    inner_join(all_irop, by = c('subject_id', 'eye', 'session')) %>%
    na_if('NULL.bmp') %>%
    select(subject_id, session, eye, ground_truth, posterior, nasal, temporal, inferior, superior)

split_5 <- read_excel('/Volumes/External/irop_data/all_splits_master_file.xlsx', sheet = 5) %>%
    clean_names() %>%
    separate(original_files, c('subject_id', NA, 'session', NA, 'eye', NA), sep = '_') %>%
    inner_join(all_irop, by = c('subject_id', 'eye', 'session')) %>%
    na_if('NULL.bmp') %>%
    select(subject_id, session, eye, ground_truth, posterior, nasal, temporal, inferior, superior) %>%
    drop_na(posterior)
```



```{r}
gan_train <- split_1 %>%
    bind_rows(split_2, split_3) %>%
    gather('view', 'image_id', posterior:superior) %>%
    drop_na() %>%
    filter(image_id != '49318.bmp',
           view == 'posterior') # %>%
    # group_by(ground_truth) %>%
    # add_count() %>%
    # slice(sample(row_number(), min(.$n))) %>%
    # select(-n)


cnn_val <- split_4 %>%
    drop_na(posterior) %>%
    group_by(ground_truth) %>%
    add_count() %>%
    slice(sample(row_number(), min(.$n))) %>%
    select(-n)

cnn_test <- split_5 %>%
    drop_na(posterior)
```


```{r}
dir_create('./out/gan/No')
dir_create('./out/gan/Pre-Plus')
dir_create('./out/gan/Plus')
```


```{r}
src = '/Volumes/External/irop_data/segmentations'

dst = './out/gan/'
file_copy(paste(src, gan_train$image_id, sep = '/'),
          paste(dst, gan_train$ground_truth, gan_train$image_id, sep = '/'),
          overwrite = TRUE)
```


## IMPORTANT: Clean images before training models!
